#!/bin/bash

set -e

# We're just sourcing the central benchmark, typically people will just put
# their benchmarks in one file.
. actions/benchmark

# run_benchmark ubuntu_qrt_apparmor ubuntu_qrt_kernel ubuntu_qrt_kernel_aslr_collisions ubuntu_qrt_kernel_hardening ubuntu_qrt_kernel_panic ubuntu_qrt_kernel_security
