#!/bin/bash

set -eux

# We're just sourcing the central benchmark, typically people will just put
# their benchmarks in one file.

. actions/benchmark

params=`action-get testnames`
run_benchmark $params
